image: maven:3.6.1

definitions:
  steps:
    - step: &STAGE-IO
        name: STAGE-IO
        script:
          - pipe: sig-devsecops/intelligent-security-scan:0.1.2
            variables:
              STAGE: 'IO'
        artifacts:
          - pipe.meta.env

    - step: &SAST-SCANNING
        name: SAST SCANNING
        caches:
          - maven
        script:
          - source pipe.meta.env
          - >
            if [ "$IS_SAST_ENABLED" = false ]; then
              echo "SAST Scanning is disbled."
              exit 0
            fi
          - wget -q $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
          - unzip -j polaris_cli-linux64.zip -d /tmp
          - /tmp/polaris analyze -w
        services:
          - docker



    - step: &SAST-SCANNING-INCREMENTAL
        name: INCREMENTAL SAST SCANNING
        caches:
          - maven
        script:
          - source pipe.meta.env
          - >
            if [ "$IS_SAST_ENABLED" = false ]; then
              echo "SAST Scanning is disbled."
              exit 0
            fi
          - git fetch --verbose http://bitbucket.org/$BITBUCKET_REPO_FULL_NAME $BITBUCKET_PR_DESTINATION_BRANCH:target_branch 
          - git tag -f fork_point $(git merge-base target_branch $BITBUCKET_COMMIT)
          - git diff --name-only fork_point $BITBUCKET_COMMIT | egrep '[.java]$' >> "polaris-files-to-scan.txt"
          - cat polaris-files-to-scan.txt
          - wget $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
          - unzip -j polaris_cli-linux64.zip
          - export POLARIS_FF_ENABLE_COVERITY_INCREMENTAL=true
          - ./polaris -c polaris.yml analyze -w --coverity-ignore-capture-failure --incremental polaris-files-to-scan.txt | tee polaris-output.txt
        services:
          - docker

    - step: &SCA-SCANNING
        name: SCA SCANNING
        caches:
          - maven
        script:
          - source pipe.meta.env
          - >
            if [ "$IS_SCA_ENABLED" = false ]; then
              echo "SCA Scanning is disbled."
              exit 0
            fi
          - >
            bash <(curl -s https://detect.synopsys.com/detect.sh) \
            --blackduck.url="https://bizdevhub.blackducksoftware.com" \
            --blackduck.api.token="YWY0MzUyZmUtNzExNi00MDY3LWFhNTAtNWFiM2IxZTUyMmFiOjg2NWM0MmNjLWY3ZmYtNDE5YS1hZTEwLTE5Yjg0YWI2ZDQ5Yw" \
            --detect.tools="SIGNATURE_SCAN,DETECTOR" \
            --detect.force.success="false" \
            --detect.wait.for.results="false" \
            --detect.policy.check.fail.on.severities="UNSPECIFIED" \
            --logging.level.com.synopsys.integration="INFO"
        services:
          - docker

    - step: &STAGE-WORKFLOW
        name: STAGE-WORKFLOW
        script:
          - source pipe.meta.env
          - >
            if [ "$IS_SAST_ENABLED" = false ] && [ "$IS_SCA_ENABLED" = false ]; then
              echo "Not performing WORKFLOW stage as all scanning activities are disabled."
              exit 0
            fi
          - pipe: sig-devsecops/intelligent-security-scan:0.1.2
            variables:
              STAGE: 'WORKFLOW'
              IS_SAST_ENABLED: $IS_SAST_ENABLED
              IS_SCA_ENABLED: $IS_SCA_ENABLED     
    
  services:
    docker:
      memory: 3072

pipelines:
  branches:
    master:
      - step: *STAGE-IO

      - parallel:
        - step: *SAST-SCANNING
        - step: *SCA-SCANNING

      - step: *STAGE-WORKFLOW

  pull-requests:
    '**':
      - step: *STAGE-IO

      - parallel:
        - step: *SAST-SCANNING-INCREMENTAL
        - step: *SCA-SCANNING

      - step: *STAGE-WORKFLOW
      